### PR TITLE
Add a const for Opus (this is a semi-fix until re-sampling is integ…

### PR DESCRIPTION
**Pull request by RustoMCSpit**
this only introduces a const, it doesnt call on it. im on phone rn and navigating a github code base is nightmarish on phone

### CODE REVIEW

**Comment by tibbi** [comment]
why should we add something unused?

**Comment by RustoMCSpit** [comment]
> why should we add something unused?

https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/164

**Comment by tibbi** [comment]
well, this PR doesnt add anything though, just an unused constant

**Comment by RustoMCSpit** [comment]
> well, this PR doesnt add anything though, just an unused constant

let me work on it when i have the time

**Pull request closed without merging**
