### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by PatrykMis**

### CODE REVIEW

**Comment by Aga-C** [comment]
"Występ głosowy" doesn't make any sense. I think the best translation is "Wydajność głosu". Also, I'd write "Domyślne systemowe" instead of "Domyślne dla Androida".

BTW. These strings were already translated on Weblate.

**Comment by PatrykMis** [comment]
It cannot be "wydajność głosu":

Voice Performance:

> Source for capturing audio meant to be processed in real time and played back for live performance (e.g karaoke).

(source: <https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#VOICE_PERFORMANCE>

**Comment by Aga-C** [comment]
But it means, that it focuses more on performance (to work seamlessly in real time) than the quality of the audio recording, thus "wydajność" suits better.

**Comment by PatrykMis** [comment]
the "performance" has two meanings in Polish - "wydajność" and "występ". So quoting above from documentation it relates to "występ", not "wydajność".

**Comment by Aga-C** [comment]
Yes, but the app doesn't work in real time, so it doesn't make any sense and no one will know what it means. And what this setting does, it puts performance (as in "wydajność") over quality. That's why I think "wydajność" suits better than "występ", although documentation can be understood in both ways.

**Comment by PatrykMis** [comment]
It is optimized for latency, not for quality so we should avoid possible misunderstanding of this option.

**Comment by Aga-C** [comment]
But in practice it decreases quality. Maybe other wording would suit better, but "Występ głosowy" as sound source sounds strange and for sure most users won't know what it means, even technical people.

**Comment by PatrykMis** [comment]
Regarding "Domyślne dla systemu": let's leave as it is. If it will be "Domyślne dla systemu" it would be "System default" not "Android default". I think we should avoid changing the meaning.

Btw. that's why I use all apps in English, because translators often are trying to improve meaning which is not good practice.

**Comment by PatrykMis** [comment]
@Aga-C yeah, "Voice performance" is very problematic term to translate without additional explanation.

**Comment by Aga-C** [comment]
It can be "Domyślne androidowe", just "dla Androida" gives wrong meaning and in English it would be "Default for Android". Also, in other Simple Apps it's always "System default", so I wanted to keep consistency between the apps.

**Comment by PatrykMis** [comment]
Do whatever you want with this. I'm not saying my point of view is only and correct, just explained why I translated that way.

**Pull request merged**
