### PR TITLE
WIP: Audio editor

### PR DESCRIPTION
**Pull request by esensar**

### CODE REVIEW

**Comment by tibbi** [comment]
crashes to me on android 13 at pressing Edit
Process: com.simplemobiletools.voicerecorder.debug, PID: 11663
                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simplemobiletools.voicerecorder.debug/com.simplemobiletools.voicerecorder.activities.EditRecordingActivity}: java.util.NoSuchElementException
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8762)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                 Caused by: java.util.NoSuchElementException
                 	at kotlin.collections.CollectionsKt___CollectionsKt.maxOrThrow(_Collections.kt:1920)
                 	at com.simplemobiletools.voicerecorder.views.AudioEditorView.putAmplitudes(AudioEditorView.kt:93)
                 	at com.simplemobiletools.voicerecorder.activities.EditRecordingActivity.updateVisualization$lambda$2(EditRecordingActivity.kt:94)
                 	at com.simplemobiletools.voicerecorder.activities.EditRecordingActivity.$r8$lambda$BYKvXRDXkoSunAemCSj17rGDFeM(Unknown Source:0)
                 	at com.simplemobiletools.voicerecorder.activities.EditRecordingActivity$$ExternalSyntheticLambda2.onSuccess(Unknown Source:2)
                 	at linc.com.amplituda.AmplitudaProcessingOutput.get(AmplitudaProcessingOutput.java:50)
                 	at linc.com.amplituda.AmplitudaProcessingOutput.get(AmplitudaProcessingOutput.java:58)
                 	at com.simplemobiletools.voicerecorder.activities.EditRecordingActivity.updateVisualization(EditRecordingActivity.kt:91)
                 	at com.simplemobiletools.voicerecorder.activities.EditRecordingActivity.onCreate(EditRecordingActivity.kt:76)
                 	at android.app.Activity.performCreate(Activity.java:8591)
                 	at android.app.Activity.performCreate(Activity.java:8570)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)

**Comment by tibbi** [comment]
it doesnt really show anything useful and the bottom controls are useless on that view. This is pretty far from done :/

**Comment by esensar** [comment]
> it doesnt really show anything useful and the bottom controls are useless on that view. This is pretty far from done :/

Well yeah, this is an early draft. I wanted to make sure that I am moving in the right direction.

I am not really sure what exactly you mean, I guess the issue is that the controls are hidden until you start dragging on the waveform. When it comes to the bottom controls, yeah, I haven't removed some of them, but I think the player is still needed, or at least just the play and pause buttons, to be able to listen to parts that you want to cut out.

When it comes to positioning of the controls, for testing right now I just put them all in an action bar menu since that was the quickest for me. Would it make sense to make it a bottom bar, something like in Simple Gallery editor instead?

**Comment by tibbi** [comment]
we should definitely show the selected times of start and end or the selected area, with the option to insert values there manually on click. The bottom should just have play/pause so do not reuse the bottom bar, create a new one. Try checking some popular voice editor how are they doing it.

**Comment by RustoMCSpit** [comment]
not totally sure what this is about cause my phone screen is bugging out but if youre adding new ui could there be buttons for:

1) repeat button
2) repeat section of recording
3) duplicate part of recording (as in save a part and have it pasted into a totallt new recording)
4) repeat multiple recordings
5) speed up / down 
6) pitch up / down.
7) custom tags for recordings 
8) vorbis comments / id3 tags

sorry if i misunderstood the pull my phone screen is throwing fits rn

**Comment by esensar** [comment]
> not totally sure what this is about cause my phone screen is bugging out but if youre adding new ui could there be buttons for:
> 
>     1. repeat button
> 
>     2. repeat section of recording
> 
>     3. duplicate part of recording (as in save a part and have it pasted into a totallt new recording)
> 
>     4. repeat multiple recordings
> 
>     5. speed up / down
> 
>     6. pitch up / down.
> 
>     7. custom tags for recordings
> 
>     8. vorbis comments / id3 tags
> 
> 
> sorry if i misunderstood the pull my phone screen is throwing fits rn

Thank you for the early feedback. This is still very early work in progress PR, so I am not sure when I will be done with it, since at this time it is definitely not usable, but thank you for the suggestions!

**Comment by RustoMCSpit** [comment]
> > not totally sure what this is about cause my phone screen is bugging out but if youre adding new ui could there be buttons for:
> > ```
> > 1. repeat button
> > 
> > 2. repeat section of recording
> > 
> > 3. duplicate part of recording (as in save a part and have it pasted into a totallt new recording)
> > 
> > 4. repeat multiple recordings
> > 
> > 5. speed up / down
> > 
> > 6. pitch up / down.
> > 
> > 7. custom tags for recordings
> > 
> > 8. vorbis comments / id3 tags
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sorry if i misunderstood the pull my phone screen is throwing fits rn
> 
> Thank you for the early feedback. This is still very early work in progress PR, so I am not sure when I will be done with it, since at this time it is definitely not usable, but thank you for the suggestions!

yourr welcome, just added two new points

**Comment by tibbi** [comment]
some parts of the code accidentally got into master branch and after I compiled the release mode, the app size increased from 10 to 70mb, which is way too huge. Can we make it smaller? Because if not, it doesn make sense to continue the development this way.

**Comment by esensar** [comment]
> some parts of the code accidentally got into master branch and after I compiled the release mode, the app size increased from 10 to 70mb, which is way too huge. Can we make it smaller? Because if not, it doesn make sense to continue the development this way, with these libraries.

Hmm, I will take a look. These libraries depend on native libraries, so it might be related to that.

**Pull request closed without merging**
