### PR TITLE
Clarify m4a is not FOSS

### PR DESCRIPTION
**Pull request by RustoMCSpit**

### CODE REVIEW

**Comment by tibbi** [comment]
why have you changed all the code formatting? Format the code properly please

**Comment by RustoMCSpit** [comment]
> why have you changed all the code formatting? Format the code properly please
 
i moved one of the comments

**Comment by tibbi** [comment]
that code is just ridiculously bad... Thanks though

**Comment by RustoMCSpit** [comment]
> that code is just ridiculously bad... Thanks though
oh sorry, whats wronf with it (im a beginner)

**Pull request closed without merging**
